spring.application.name=concert
spring.mvc.throw-exception-if-no-handler-found=true


spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1
spring.datasource.username=sa2
spring.datasource.password=sa2

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console