-- 테이블 삭제
DROP TABLE IF EXISTS concert CASCADE;
DROP TABLE IF EXISTS concert_schedule CASCADE;
DROP TABLE IF EXISTS concert_seat CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS queue CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS token CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 테이블 생성
CREATE TABLE users (
    user_id VARCHAR(255) NOT NULL PRIMARY KEY,
    token VARCHAR(255),
    balance BIGINT DEFAULT 0
);

CREATE TABLE concert (
    concert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_name VARCHAR(255) NOT NULL,
    age BIGINT DEFAULT 0,
    created_at TIMESTAMP
);

CREATE TABLE concert_schedule (
    concert_id BIGINT NOT NULL,
    concert_dy VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    PRIMARY KEY (concert_id, concert_dy)
);

CREATE TABLE concert_seat (
    concert_id BIGINT NOT NULL,
    concert_dy VARCHAR(255) NOT NULL,
    seat_no BIGINT NOT NULL,
    seat_grade VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    state VARCHAR(255) DEFAULT 'AVAILABLE',
    version INT DEFAULT 0 ,
    PRIMARY KEY (concert_id, concert_dy, seat_no)
);

CREATE TABLE reservation (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id BIGINT,
    concert_dy VARCHAR(255),
    seat_no BIGINT,
    seat_grade VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    temp_reserve_user_id VARCHAR(255),
    temp_reserve_expired_at TIMESTAMP
);

CREATE TABLE payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT,
    payment_date TIMESTAMP ,
    price BIGINT
);

CREATE TABLE queue (
    queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    state VARCHAR(255) DEFAULT 'WAIT',
    created_at TIMESTAMP NOT NULL,
    active_at TIMESTAMP,
    expired_at TIMESTAMP
);
